version: '2'
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: development
    links:
      - node
    ports:
      - 80:80
    volumes:
      - ./static:/usr/share/nginx/html
      - /usr/share/nginx/html/dist
      - /usr/share/nginx/html/node_modules
  couch:
    build:
      context: .
      dockerfile: Dockerfile.couch
    container_name: couch
    expose:
      - 5984
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    links:
      - node
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node
    environment:
      NODE_ENV: ${NODE_ENV}
    expose:
      - 3000
    links:
      - couch
    volumes:
      - ./server:/root
      - /root/dist
      - /root/node_modules
